### PR TITLE
Multidevice Beta

### PR DESCRIPTION
**Pull request by Auties00**
Multidevice beta

### CODE REVIEW

**Comment by Auties00** [comment]
Uhm so this update will break everything because it's kind of a new version of ww web. So might as well make it better :)

**Comment by jefaokpta** [comment]
May the force be with you!

**Comment by Tiebe** [comment]
@Auties00 Would you be able to publish the more recent sources for ModernProtoc? With the current repository it doesn't seem to work.

**Comment by Auties00** [comment]
> @Auties00 Would you be able to publish the more recent sources for ModernProtoc? With the current repository it doesn't seem to work.

As you can see in the latest commit, I'm working on an update. Once it's done I'll release it

**Comment by Tiebe** [comment]
> > @Auties00 Would you be able to publish the more recent sources for ModernProtoc? With the current repository it doesn't seem to work.
> 
> As you can see in the latest commit, I'm working on an update. Once it's done I'll release it

Awesome, thank you

**Comment by Vaibbs** [comment]
Multidevice is not in beta anymore right? So that means you can't disable it anymore (At least I can't find any setting in there).

It is giving me an exception after scanning, so my phone is allowing that connection and I can't see it in the list and that can be potentially dangerous or it just fails and there is nothing to worry about?

Also, does that mean we can't make use of this until you figure out the new auth process?

With the new WhatsApp web, it shows the wss messages in binary, so how I am supposed to find the proper description and short description?

**Comment by Auties00** [comment]
> Multidevice is not in beta anymore right? So that means you can't disable it anymore (At least I can't find any setting in there).
> 
> It is giving me an exception after scanning, so my phone is allowing that connection and I can't see it in the list and that can be potentially dangerous or it just fails and there is nothing to worry about?
> 
> Also, does that mean we can't make use of this until you figure out the new auth process?
> 
> With the new WhatsApp web, it shows the wss messages in binary, so how I am supposed to find the proper description and short description?

Yeah you'll have to wait

**Comment by jefaokpta** [comment]
Congrats @Auties00 ! I'm very excited to test it!

**Comment by Auties00** [comment]
> Congrats @Auties00 ! I'm very excited to test it!

It should be possible now as I pushed all the artifacts to maven central. Though, it might not work as of now. In a couple of days it should be stable I hope. (Btw just added full support for media messages)

**Pull request merged**
