### PR TITLE
Adds documentation for building the project.

### PR DESCRIPTION
**Pull request by jamiguet**
I took the liberty of opening a PR to add instruction of how to build the project.
I am submitting it here for your consideration and approval.

Happy to assist with the development of the library as I have a few interesting use cases.
Also I have noticed it is lacking tests, which may help improving the quality of the library and its integrations.

Let me know If I could assist with anything else.

### CODE REVIEW

**Comment by Auties00** [comment]
Hello,
this looks perfect. Although I forgot to tell you that you have also to modify the version of lombok that delombok uses. To do that you need to navigate to:
```
cd ${user.home}/.m2/repository/org/projectlombok/lombok-maven/1.18.18.0
nano lombok-maven-1.18.18.0.pom
```

Now look for the property lombok.version, on line 71, and replace it from 1.18.18 to fixed. This should also fixed the [issue you opened ](https://github.com/Auties00/WhatsappWeb4j/issues/7). If this work we can add it into the README.md and merge it with the master branch

**Comment by jamiguet** [comment]
Thank you.
I will try that as soon as I can.

I will add this to the documentation but ideally there should not be the need to edit poms and so on as that make the build process frail.
Could the version built by ant be used as is and referenced in the pom of the lib?

**Comment by Auties00** [comment]
> n but ideally there should not be the need to edit poms and so on as that mak

As soon as lombok merges that branch there will be no need to do all of this as the edge version gets built every week.
https://projectlombok.org/download-edge

**Comment by jamiguet** [comment]
Updated the PR documenting the issue.
Feel free to approve and merge to your convenience.

**Pull request merged**
